### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by Tekl** [carolineartz/rendered_images_for_folding_text#4]
Even with the example files

I'm using FT 2.2 on macOS 10.13.3Beta.

**Comment by carolineartz** [comment]
hey @Tekl! Sorry I don't know how I missed this. I'll look into this over the weekend

**Comment by carolineartz** [comment]
hm, i just cloned the repo and tried it on my machine and it works fine for me -- 

![kapture 2018-02-09 at 18 40 20](https://user-images.githubusercontent.com/2850369/36056307-005307f8-0dc9-11e8-9a5a-3562bdbe2e86.gif)

![image](https://user-images.githubusercontent.com/2850369/36056309-051e003a-0dc9-11e8-8983-87dec4114752.png)

@Tekl would you mind providing more info or seeing if you can still reproduce the issue or otherwise close? Thanks!

**Comment by Tekl** [comment]
Ah, I didn't understand that I have to add "@img" to the lines, but it still does not work with local files on my machine (same OS and same FT version):

![bildschirmfoto 2018-02-10 um 13 50 54](https://user-images.githubusercontent.com/3667947/36062287-748736d0-0e69-11e8-98e2-f20b3c7e1af0.png)

**Comment by carolineartz** [comment]
Drag the image into the editor to get the full path to the local image, not just the image name.

**Comment by Tekl** [comment]
Okay, that works, but that's not what I want. And it only works on multiple computers when the user folders have the same name.

**Comment by carolineartz** [comment]
@Tekl sorry it's not what you're looking for. However, this plugin is working exactly as expected and as documented in the README. 

Feel free to take out a PR if you think something could be improved!

Tip: if you need to open the docs on different machines, use a free hosting service to serve your images and link to them there.

closing: not an issue.

**Comment by Tekl** [comment]
Thanks for helping out, Caroline. Indeed it's not what I've expected.

I don't understand what you mean by "take out a PR". Of course working with relative images would be an improvement. I know it could be hard to achieve with CSS, but maybe the Plug-in could inject the document's absolute path into the CSS. I would try it myself If I had the time and skills.
